<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches [
    <!ELEMENT coches (coche+)>
    <!ELEMENT coche (marca,modelo,puertas,color,precio)>
    <!ATTLIST coche matricula CDATA #REQUIRED>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT puertas (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio venta CDATA #REQUIRED>
]>
<coches>
    <coche matricula="1386KGH">
        <marca>Citr√∂en</marca>
        <modelo>C3 aircross</modelo>
        <puertas>5</puertas>
        <color>Gris</color>
        <precio venta="nuevo">22000</precio>
    </coche>
    <coche matricula="4367YTW">
        <marca>Seat</marca>
        <modelo>Leon</modelo>
        <puertas>5</puertas>
        <color>Rojo</color>
        <precio venta="ocasion">15000</precio>
    </coche>
</coches>