<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegios [
    <!ELEMENT colegios (alumnos, profes)>
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre,apellido,matricula,activo?)>
    <!ATTLIST alumno expediente CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT activo EMPTY>
    <!ELEMENT profes (profe+)>
    <!ELEMENT profe (nombre,curso,foto)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT foto (#PCDATA)> 
]>
<colegios>
    <alumnos>
        <alumno expediente="1">
            <nombre>Encarnación</nombre>
            <apellido>Carrillo</apellido>
            <matricula>DAW</matricula>
            <activo />
        </alumno>
        <alumno expediente="2">
            <nombre>Rafael</nombre>
            <apellido>López</apellido>
            <matricula>DAM</matricula>
        </alumno>
    </alumnos>
    <profes>
        <profe>
            <nombre>Óscar</nombre>
            <curso>DAW</curso>
            <foto>imagenoscar.jpg</foto>
        </profe>
    </profes>
</colegios>