<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles [
<!ELEMENT arboles (arbol)+>
<!ELEMENT arbol (nombre , nombre_comun , vegetacion , altura , forma_y_estructura , color_primavera , color_otono? , resistencia_heladas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nombre_comun (#PCDATA)>
<!ELEMENT vegetacion (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT forma_y_estructura (#PCDATA)>
<!ELEMENT color_primavera (#PCDATA)>
<!ELEMENT resistencia_heladas (#PCDATA)>
<!ELEMENT color_otono (#PCDATA)>
]>
<arboles>
  <arbol>
    <nombre>Acer monspessulanum</nombre>
    <nombre_comun>Arce de Montpellier, Arce menor</nombre_comun>
    <vegetacion>Caducifolio</vegetacion>
    <altura>De 6 a 10 metros</altura>
    <forma_y_estructura>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</forma_y_estructura>
    <color_primavera>Haz verde brillante, envés verde blanquecino</color_primavera>
    <resistencia_heladas>Heladas fuertes (hasta -15°C)</resistencia_heladas>
  </arbol>
  <arbol>
    <nombre>Olea europea</nombre>
    <nombre_comun>Olivo</nombre_comun>
    <vegetacion>Perenne</vegetacion>
    <altura>De 8 a 15 metros</altura>
    <forma_y_estructura>Copa irregular. Tronco principal irregular con bifurcaciones. Ramaje tortuoso</forma_y_estructura>
    <color_primavera>Haz verde oscuro, envés verde plateado</color_primavera>
    <resistencia_heladas>Heladas medias (hasta -10°C)</resistencia_heladas>
  </arbol>
  <arbol>
    <nombre>Platanus orientalis</nombre>
    <nombre_comun>Plátano</nombre_comun>
    <vegetacion>Caducifolio</vegetacion>
    <altura>De 20 a 25 metros</altura>
    <forma_y_estructura>Copa ovoide. Tronco principal recto. Ramaje expandido</forma_y_estructura>
    <color_primavera>Haz verde medio, envés verde claro</color_primavera>
    <color_otono>Ocre</color_otono>
    <resistencia_heladas>Heladas fuertes (hasta -20°C)</resistencia_heladas>
  </arbol>
  <arbol>
    <nombre>Quercus ilex</nombre>
    <nombre_comun>Encina</nombre_comun>
    <vegetacion>Perenne</vegetacion>
    <altura>En torno a 25 metros</altura>
    <forma_y_estructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma_y_estructura>
    <color_primavera>Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</color_primavera>
    <resistencia_heladas>Heladas fuertes (hasta -15°C)</resistencia_heladas>
  </arbol>
</arboles>
