=== iesgrancapitan-llmm/mi-primera-pagina-web-oscarmcc/T5.4/datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:simpleType name="DNITipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{8}[A-Z]?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MatriculaTipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}\s?[B-DF-HJ-NP-TV-Z][A-Z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MACDireccionTipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9A-Fa-f]{2}([:-])?){5}([0-9A-Fa-f]{2})"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="IPDireccionTipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NumeroDecimalTipo">
    <xs:restriction base="xs:decimal">
      <xs:pattern value="^\d+(\.\d{1,2})?$"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dni" type="DNITipo"/>
        <xs:element name="matricula" type="MatriculaTipo"/>
        <xs:element name="direccion_MAC" type="MACDireccionTipo"/>
        <xs:element name="direccion_IP" type="IPDireccionTipo"/>
        <xs:element name="numero_con_dos_decimales" type="NumeroDecimalTipo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iesgrancapitan-llmm/mi-primera-pagina-web-oscarmcc/T5.4/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datos.xsd">
    <dni>12345678Z</dni>
    <!-- <dni>12345678z</dni> -->
    <!-- <dni>12345678 Z</dni> -->
    <!-- <dni>12345678-Z</dni> -->
    
    <matricula>1234 BCD</matricula>
    <matricula>5678 ZYX</matricula>
<!--<matricula>1234 ABC</matricula> -->
    <!--<matricula>1234 QBC</matricula>-->
    <!--<matricula>1234 MNÑ</matricula>  -->
    
    <direccion_MAC>AB-CD-F1-23-45-67</direccion_MAC>
    <direccion_MAC>AB:CD:F1:23:45:67</direccion_MAC>
    <direccion_MAC>ABCDF1234567</direccion_MAC>
    <direccion_MAC>AB:CDF1:23:45-67</direccion_MAC> <!-- Inválida -->
    
    <direccion_IP>0.0.0.0</direccion_IP>
    <direccion_IP>14.255.1.2</direccion_IP>
    <!--<direccion_IP>09.1.2.3</direccion_IP>-->
    <!--<direccion_IP>1.260.4.5</direccion_IP> -->
    <!--<direccion_IP>09.6.5.4</direccion_IP>-->
    <!--<direccion_IP>1.2.3.011</direccion_IP>-->
    
    <numero_con_dos_decimales>123.45</numero_con_dos_decimales>
    <numero_con_dos_decimales>456.789</numero_con_dos_decimales> <!-- Inválida -->
</datos>
